### ISSUE TITLE
Create Ship Directory

### ISSUE THREAD

**Issue by JessaWitzel** [JessaWitzel/battleship#5]
Create a dictionary of ship types and lengths that can be used when creating your Battleship Board. https://en.wikipedia.org/wiki/Battleship_(game)

Letter  Class of ship   Size
'C'         Carrier         5
'B'         Battleship      4
'R'         Cruiser         3
'S'         Submarine   3
'D'         Destroyer   2

**Comment by wwitzel3** [comment]
I like this, I think we should use `U` for Submarine (U-Boat) :)
